[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
com_logger = "0.1.1"
bootloader_api = { version = "0.11.0" }
log = "0.4.17"
vga = "0.2.7"
